version: latest

services:
  redis:
    image: redis:7.0.13-alpine
    container_name: redis
    restart: always
    volumes:
      - redis:/data
    command: redis-server --save 60 1 --loglevel warning

  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: hibernate
    volumes:
      - mysql:/var/lib/mysql
    restart: always

  api:
    container_name: hibernate-api
    depends_on:
      - redis
      - mysql
    build: ./
    ports:
      - 8082:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=123456
      - DB_DATABASE=hibernate

volumes:
  redis:
    driver: local
  mysql:
    driver: local