spring:
  application:
    name: hibernate
  datasource:
    password: 123456
    url: jdbc:mysql://mysql:3306/hibernate
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
